---
abstract: 'interact with a F<Bus Pirate> device'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Device-BusPirate
provides:
  Device::BusPirate:
    file: lib/Device/BusPirate.pm
    version: '0.06'
  Device::BusPirate::Chip:
    file: lib/Device/BusPirate/Chip.pm
    version: '0.06'
  Device::BusPirate::Mode:
    file: lib/Device/BusPirate/Mode.pm
    version: '0.06'
  Device::BusPirate::Mode::BB:
    file: lib/Device/BusPirate/Mode/BB.pm
    version: '0.06'
  Device::BusPirate::Mode::I2C:
    file: lib/Device/BusPirate/Mode/I2C.pm
    version: '0.06'
  Device::BusPirate::Mode::SPI:
    file: lib/Device/BusPirate/Mode/SPI.pm
    version: '0.06'
requires:
  Future: '0'
  Future::Utils: '0'
  IO::Termios: '0'
  Module::Pluggable: '0'
  Time::HiRes: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.06'
